### ISSUE TITLE
Please make the font bigger

### ISSUE THREAD

**Issue by dg01d** [erkin/gophwr#4]
Feature request as opposed to a bug report, and its entirely encapsulated in the title.

On a mac screen, the font is so tiny as to be unreadable. These *mumblemumble* years old eyes just can't cope with that at all 😃

**Comment by dg01d** [comment]
I'm an idiot.

Quick change to font-size in `src/config.rkt` and I'm away at the races.

Great program.

**Comment by erkin** [comment]
@dg01d You might be pleased to hear that you can now override default values in a config file in v0.5.0. :-)
