### ISSUE TITLE
First Line of Menus offset

### ISSUE THREAD

**Issue by dg01d** [erkin/gophwr#5]
The first line on many gopher menus is offset from the remaining entries.

See attached screenshot.

This only appears to occur where there is no other information preceding the first menu item, i.e. Bongusta! appears normally.
<img width="200" alt="Screenshot 2019-06-26 at 15 43 41" src="https://user-images.githubusercontent.com/1061809/60189752-5ba2fc80-9829-11e9-981c-6151996dedb3.png">

**Comment by erkin** [comment]
I've been trying to figure out why this happens, but the change in text styling in v0.5.6 seems to fix this somehow. (+ performance improvement)

@dg01d Can you check to see if it persists on your end?

**Comment by erkin** [comment]
Based on what you said on IRC, I hereby declare this issue solved.
